# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

# on:
#   push:
#     branches:
#       - "main"

on:
  repository_dispatch:
    types: [release_docker_image]

jobs:
  docker_publish_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        working-directory: ./packages/lpms-server
        env:
          LPMS_SERVER_TAG: ${{secrets.LPMS_SERVER_TAG}}
        run: ./build.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        working-directory: ./packages/lpms-server
        run: docker push windingtree/lpms-server:${{secrets.LPMS_SERVER_TAG}}
